on: [push, workflow_dispatch]
jobs:
  cicd:
    # https://github.com/internetarchive/cicd
    uses: internetarchive/cicd/.github/workflows/cicd.yml@main
    with:
      NOMAD_VAR_PORTS: '{ 80 = "http" }'
      NOMAD_VAR_MEMORY: 100
      NO_TEST: true
    secrets:
      NOMAD_TOKEN_EXT: ${{ secrets.NOMAD_TOKEN_EXT }}
